name: CI

on:
  pull_request:
  push:
    branches:
      - '**' # run on any branch
    tags-ignore:
      - 'v*.*.*' # except ones that are release tags
    paths-ignore:
      - 'README.md' # or ones that only contain changes to the readme / license
      - 'LICENSE'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: lint
        run: test -z "$(gofmt -s -d .)"
      - name: ensure tidy gomod
        run: test -z "$(go mod tidy && git status --porcelain go.mod go.sum)"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --snapshot --skip-publish --rm-dist